# Generated by Django 3.0.1 on 2020-02-13 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='past',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('fro', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('dated', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='external_letter',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internal_letter',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='external_letter',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.past'),
        ),
        migrations.AddField(
            model_name='internal_letter',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.past'),
        ),
    ]
