# Generated by Django 3.0.1 on 2020-02-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200213_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='external_letter',
            old_name='referred',
            new_name='referred_to',
        ),
        migrations.RenameField(
            model_name='internal_letter',
            old_name='referred',
            new_name='referred_to',
        ),
    ]
