# Generated by Django 3.0.1 on 2020-02-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200213_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='external_past',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='internal_past',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
