# Generated by Django 3.0.1 on 2020-02-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200213_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='external_letter',
            old_name='fromm',
            new_name='From',
        ),
        migrations.RenameField(
            model_name='internal_letter',
            old_name='fromm',
            new_name='From',
        ),
    ]
