# Generated by Django 3.0.1 on 2020-02-13 12:05

import datetime
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200213_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_letter',
            name='receipt_date',
            field=models.DateField(default=datetime.date(2020, 2, 13)),
        ),
        migrations.AlterField(
            model_name='external_letter',
            name='si_no',
            field=models.IntegerField(default=home.models.external_letter.number),
        ),
        migrations.AlterField(
            model_name='internal_letter',
            name='in_date',
            field=models.DateField(default=datetime.date(2020, 2, 13)),
        ),
    ]
